version: "3"

services:
  node1:
    image: vrrp-test:0.1
    container_name: node1
    hostname: node1
    tty: true
    environment:
      VRRP_IF: "eth0"
      VRRP_RID: 50
      VRRP_PRIORITY: 100
      VRRP_VIP: 172.18.0.100
      VRRP_ADVERT_INT: 3
    cap_add:
      - CAP_NET_ADMIN
      - CAP_NET_RAW
    networks:
      default:
        ipv4_address: 172.18.0.2
  node2:
    image: vrrp-test:0.1
    container_name: node2
    hostname: node2
    tty: true
    environment:
      VRRP_IF: "eth0"
      VRRP_RID: 50
      VRRP_PRIORITY: 98
      VRRP_VIP: 172.18.0.100
      VRRP_ADVERT_INT: 3
    cap_add:
      - CAP_NET_ADMIN
      - CAP_NET_RAW
    networks:
      default:
        ipv4_address: 172.18.0.3

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
